image: Visual Studio 2017

environment:
    matrix:
        - GENERATOR: "Visual Studio 15 2017 Win64"
        - GENERATOR: "Visual Studio 15 2017"

before_build:
    - mkdir build
    - cd build
    - cmake "-G%GENERATOR%" "-DDOUBLE_PRECISION=ON" ..

build_script:
    - cmake --build . --config Release

test_script:
    - ctest -C Release --output-on-failure -E FullRun
