language: cpp

matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-8
                      - cmake
          env:
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - os: osx
          osx_image: xcode10.2

before_install:
    - eval "${MATRIX_EVAL}"
    - cmake --version
    - ${CXX} --version

install:
    - mkdir build && cd build
    - cmake ..
    - make

script:
    - echo "not running any tests"
#    - ctest --output-on-failure
